[package]
name = "robots-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "^0.14.5"
prost = "^0.14.3"
tonic-prost = "^0.14.5"
tokio = { version = "^1.49.0", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-prost-build = "^0.14.5"

[[bin]]
name = "robots-server"
path = "src/server.rs"

[[bin]]
name = "robots-client"
path = "src/client.rs"
